// IFileSystemContractGenerator — scans the WinFsp.Native.IFileSystem interface at
// compile time and emits a static assertion class that callers invoke at startup
// to verify a given type implements every IFileSystem member.
//
// This is the entire point of the source generator: future-proof the
// DifferentialAdapter against silently missing new IFileSystem methods.
// If WinFsp adds a method and DifferentialAdapter doesn't override it,
// IFileSystemContract.AssertImplementedBy<DifferentialAdapter>() throws at startup.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace RamDrive.Diagnostics.DifferentialChecker.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class IFileSystemContractGenerator : IIncrementalGenerator
{
    private const string IFileSystemFqn = "WinFsp.Native.IFileSystem";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var ifs = context.CompilationProvider.Select(static (comp, _) =>
        {
            var sym = comp.GetTypeByMetadataName(IFileSystemFqn);
            if (sym == null) return null!;
            return sym;
        });

        context.RegisterSourceOutput(ifs, (spc, ifsSym) =>
        {
            if (ifsSym == null) return;

            var methods = ifsSym.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.MethodKind == MethodKind.Ordinary)
                .Select(m => m.Name)
                .Distinct()
                .OrderBy(n => n, System.StringComparer.Ordinal)
                .ToList();

            spc.AddSource("IFileSystemContract.g.cs", BuildSource(methods));
        });
    }

    private static string BuildSource(IReadOnlyList<string> methodNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine();
        sb.AppendLine("namespace RamDrive.Diagnostics.DifferentialChecker;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Compile-time-generated contract: the list of every method on WinFsp.Native.IFileSystem");
        sb.AppendLine("/// at the time this assembly was built. Used by DifferentialAdapter at startup to");
        sb.AppendLine("/// fail fast if a new IFileSystem method has been added but not wired up.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class IFileSystemContract");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Names of every ordinary method defined on IFileSystem at generator-run time.</summary>");
        sb.AppendLine("    public static readonly IReadOnlyList<string> ExpectedMethodNames = new[]");
        sb.AppendLine("    {");
        foreach (var n in methodNames)
            sb.Append("        \"").Append(n).AppendLine("\",");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Verify that <typeparamref name=\"T\"/> declares an override / re-implementation of every");
        sb.AppendLine("    /// IFileSystem member known at the time the source generator ran. Throws on drift.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void AssertImplementedBy<T>()");
        sb.AppendLine("    {");
        sb.AppendLine("        var declared = typeof(T)");
        sb.AppendLine("            .GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly)");
        sb.AppendLine("            .Select(m => m.Name)");
        sb.AppendLine("            .ToHashSet();");
        sb.AppendLine("        var missing = ExpectedMethodNames.Where(n => !declared.Contains(n)).ToList();");
        sb.AppendLine("        if (missing.Count > 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            var list = string.Join(\", \", missing);");
        sb.AppendLine("            throw new InvalidOperationException(");
        sb.AppendLine("                \"DifferentialAdapter is missing overrides for IFileSystem methods: \" + list);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
