// IFileSystemContractGenerator — scans the WinFsp.Native.IFileSystem interface at
// compile time and emits a static assertion class that callers invoke at startup
// to verify a given type implements every IFileSystem member.
//
// This is the entire point of the source generator: future-proof the
// DifferentialAdapter against silently missing new IFileSystem methods.
// If WinFsp adds a method and DifferentialAdapter doesn't override it,
// IFileSystemContract.AssertImplementedBy<DifferentialAdapter>() throws at startup.
//
// Signature-based matching: methods are identified by name + parameter type
// fully-qualified names (no count-only or name-only false matches).

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace RamDrive.Diagnostics.DifferentialChecker.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class IFileSystemContractGenerator : IIncrementalGenerator
{
    private const string IFileSystemFqn = "WinFsp.Native.IFileSystem";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var ifs = context.CompilationProvider.Select(static (comp, _) =>
        {
            var sym = comp.GetTypeByMetadataName(IFileSystemFqn);
            if (sym == null) return null!;
            return sym;
        });

        context.RegisterSourceOutput(ifs, (spc, ifsSym) =>
        {
            if (ifsSym == null) return;

            var signatures = ifsSym.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.MethodKind == MethodKind.Ordinary)
                .Select(SignatureOf)
                .Distinct()
                .OrderBy(s => s, System.StringComparer.Ordinal)
                .ToList();

            spc.AddSource("IFileSystemContract.g.cs", BuildSource(signatures));
        });
    }

    // Format: "MethodName(ParamType1,ParamType2,...)" with FQN on parameter types,
    // ref/out/in modifiers preserved. Return type intentionally excluded — interface
    // overload resolution is by parameter list, not return type.
    private static string SignatureOf(IMethodSymbol m)
    {
        var sb = new StringBuilder();
        sb.Append(m.Name).Append('(');
        var first = true;
        foreach (var p in m.Parameters)
        {
            if (!first) sb.Append(',');
            first = false;
            switch (p.RefKind)
            {
                case RefKind.Ref: sb.Append("ref "); break;
                case RefKind.Out: sb.Append("out "); break;
                case RefKind.In: sb.Append("in "); break;
            }
            AppendReflectionTypeName(sb, p.Type);
        }
        sb.Append(')');
        return sb.ToString();
    }

    // Mirror System.Type.FullName format. The runtime assertion uses Type.FullName,
    // so this MUST produce exactly the same string for matching to work.
    //   string         -> System.String
    //   byte[]         -> System.Byte[]
    //   Memory<byte>   -> System.Memory`1[[System.Byte]]
    //   nint           -> System.IntPtr
    private static void AppendReflectionTypeName(StringBuilder sb, ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol arr)
        {
            AppendReflectionTypeName(sb, arr.ElementType);
            sb.Append('[');
            for (var i = 1; i < arr.Rank; i++) sb.Append(',');
            sb.Append(']');
            return;
        }

        if (type is INamedTypeSymbol named && named.IsGenericType)
        {
            sb.Append(named.ContainingNamespace.ToDisplayString());
            sb.Append('.').Append(named.Name);
            sb.Append('`').Append(named.TypeArguments.Length);
            sb.Append("[[");
            for (var i = 0; i < named.TypeArguments.Length; i++)
            {
                if (i > 0) sb.Append("],[");
                AppendReflectionTypeName(sb, named.TypeArguments[i]);
            }
            sb.Append("]]");
            return;
        }

        if (type.SpecialType == SpecialType.System_IntPtr) { sb.Append("System.IntPtr"); return; }
        if (type.SpecialType == SpecialType.System_UIntPtr) { sb.Append("System.UIntPtr"); return; }

        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            sb.Append(type.ContainingNamespace.ToDisplayString()).Append('.');
        }
        sb.Append(type.Name);
    }

    private static string BuildSource(IReadOnlyList<string> signatures)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine();
        sb.AppendLine("namespace RamDrive.Diagnostics.DifferentialChecker;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Compile-time-generated contract: every method on WinFsp.Native.IFileSystem");
        sb.AppendLine("/// at the time this assembly was built, identified by name + parameter signature.");
        sb.AppendLine("/// Used by DifferentialAdapter at startup to fail fast if a new IFileSystem");
        sb.AppendLine("/// method has been added but not wired up.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class IFileSystemContract");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Signatures of every IFileSystem method known at generator-run time.</summary>");
        sb.AppendLine("    public static readonly IReadOnlyList<string> ExpectedSignatures = new[]");
        sb.AppendLine("    {");
        foreach (var s in signatures)
            sb.Append("        \"").Append(s.Replace("\\", "\\\\").Replace("\"", "\\\"")).AppendLine("\",");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Verify that <typeparamref name=\"T\"/> declares a public method matching every");
        sb.AppendLine("    /// IFileSystem signature known at generator-run time. Throws on drift.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void AssertImplementedBy<T>()");
        sb.AppendLine("    {");
        sb.AppendLine("        // Public-only: interface implementations on a class must be public to satisfy the interface.");
        sb.AppendLine("        // DeclaredOnly: do not match inherited members (e.g., object.GetHashCode).");
        sb.AppendLine("        var declared = typeof(T)");
        sb.AppendLine("            .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)");
        sb.AppendLine("            .Select(SignatureOf)");
        sb.AppendLine("            .ToHashSet();");
        sb.AppendLine("        var missing = ExpectedSignatures.Where(s => !declared.Contains(s)).ToList();");
        sb.AppendLine("        if (missing.Count > 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            var list = string.Join(\", \", missing);");
        sb.AppendLine("            throw new InvalidOperationException(");
        sb.AppendLine("                $\"{typeof(T).Name} is missing overrides for IFileSystem methods: {list}\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string SignatureOf(MethodInfo m)");
        sb.AppendLine("    {");
        sb.AppendLine("        var sb = new StringBuilder();");
        sb.AppendLine("        sb.Append(m.Name).Append('(');");
        sb.AppendLine("        var first = true;");
        sb.AppendLine("        foreach (var p in m.GetParameters())");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!first) sb.Append(',');");
        sb.AppendLine("            first = false;");
        sb.AppendLine("            if (p.IsOut) sb.Append(\"out \");");
        sb.AppendLine("            else if (p.ParameterType.IsByRef) sb.Append(p.IsIn ? \"in \" : \"ref \");");
        sb.AppendLine("            var t = p.ParameterType.IsByRef ? p.ParameterType.GetElementType()! : p.ParameterType;");
        sb.AppendLine("            AppendTypeName(sb, t);");
        sb.AppendLine("        }");
        sb.AppendLine("        sb.Append(')');");
        sb.AppendLine("        return sb.ToString();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // Mirror the generator's SignatureOf format exactly.");
        sb.AppendLine("    // Type.FullName includes assembly-qualified names for generic args; we strip them.");
        sb.AppendLine("    private static void AppendTypeName(StringBuilder sb, Type t)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (t.IsArray)");
        sb.AppendLine("        {");
        sb.AppendLine("            AppendTypeName(sb, t.GetElementType()!);");
        sb.AppendLine("            sb.Append('[');");
        sb.AppendLine("            for (var i = 1; i < t.GetArrayRank(); i++) sb.Append(',');");
        sb.AppendLine("            sb.Append(']');");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine("        if (t.IsGenericType)");
        sb.AppendLine("        {");
        sb.AppendLine("            var def = t.GetGenericTypeDefinition();");
        sb.AppendLine("            sb.Append(def.Namespace).Append('.').Append(def.Name);");
        sb.AppendLine("            sb.Append(\"[[\");");
        sb.AppendLine("            var args = t.GetGenericArguments();");
        sb.AppendLine("            for (var i = 0; i < args.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (i > 0) sb.Append(\"],[\");");
        sb.AppendLine("                AppendTypeName(sb, args[i]);");
        sb.AppendLine("            }");
        sb.AppendLine("            sb.Append(\"]]\");");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine("        if (!string.IsNullOrEmpty(t.Namespace)) sb.Append(t.Namespace).Append('.');");
        sb.AppendLine("        sb.Append(t.Name);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
